server:
  port: 8090

spring:
  application:
    name: car-rental-api
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car-rental-system
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
    show-sql: true 
  hikari:
    maximum-pool-size: 25               
    minimum-idle: 5                     
    idle-timeout: 30000                
    max-lifetime: 1800000               
    connection-timeout: 30000           
    leak-detection-threshold: 5000      
