server:
  port: 8090

spring:
  application:
    name: car-rental-api
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car-rental-system
    username: postgres
    password: postgre1234
  jpa:
    hibernate.ddl-auto: update
    show-sql: true 
